name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout & environment setup
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Env and temp files setup
    - name: Decode google-services.json
      env:
          GOOGLE_SERVICES_CONFIG: ${{ secrets.GOOGLE_SERVICES_CONFIG }}
      run: echo $GOOGLE_SERVICES_CONFIG > app/google-services.json
    - name: Decode release keystore
      env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
      run: echo $APP_KEYSTORE | base64 --decode > app/keystore.jks
    - name: Keystore credentials
      env:
          KEYSTORE_CREDENTIALS: ${{ secrets.KEYSTORE_CREDENTIALS }}
      run: echo $KEYSTORE_CREDENTIALS >> gradle.properties
    - name: Check credentials
      run: cat gradle.properties
    # Build itself  
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    # Release artifact  
    - name: Upload latest artifact
      env: 
        UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      run: 'curl --request POST "https://uploads.github.com/repos/hypertrack/live-app-android-hidden/releases/25722501/assets?access_token=$UPLOAD_TOKEN&name=live-app-debug.apk" --data-binary @./app/build/outputs/apk/release/app-release.apk --header "Content-Type: application/zip"'
